name: iphoto
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1488
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdffcc'
    - '#3d3840'
    - '#110000'
    - '#c38b59'
    - '#8bafc6'
  brandStrength: 0.5
  lightness: 0.9049550839699805
  saturation: 0.42348057962954044
  rhythmicContrast: 0.4506991566158831
purpose: []
